[package]
name = "rust-conversions"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
command-run = "0.13"
fehler = "1.0"
textwrap = "0.12"
