[package]
name = "rust-conversions"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
askama = "0.10"
command-run = "0.13"
fehler = "1.0"
syntect = "4.4"
textwrap = "0.12"
