[package]
name = "rust-conversions"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
askama = "0.11"
command-run = "1.1"
fehler = "1.0"
syntect = "5.0"
textwrap = "0.15"
